apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: chat-app

spec:
  type: NodePort
  selector:
    app: chat-frontend      # exact label match karna zaroori — deployment.yml se confirm kar
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080