apiVersion: v1
kind: Service

metadata:
  name: chat-mongodb-service
  namespace: chat-app

spec:
  selector:
    app: chat-mongodb

  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP

  type: ClusterIP